replicaCount: 1

image:
  repository: registry.saas.hand-china.com/hitoa/elasticsearch-kb
  tag: 7.2-elasticsearch-kb
  pullPolicy: IfNotPresent

service:
  port: 9200

env:
  open:
    discovery.type: single-node
    ES_JAVA_OPTS: -Xms512m -Xmx512m

logs:
  parser: docker

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.5Gi
  requests:
    # cpu: 100m
    memory: 1Gi