replicaCount: 1

image:
  repository: registry.cn-shanghai.aliyuncs.com/choerodon/elasticsearch-kb
  tag: 7.2-elasticsearch-kb
  pullPolicy: IfNotPresent

service:
  # 是否创建k8s service
  enabled: true
  # service类型
  type: ClusterIP
  # service端口
  port: 9200
  # service名称
  name: elasticsearch-kb

env:
  open:
    discovery.type: single-node
    ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    bootstrap.memory_lock: true

logs:
  parser: docker

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.5Gi
  requests:
    # cpu: 100m
    memory: 1Gi